### ISSUE TITLE
Strategies for higher write throughput.

### ISSUE THREAD

**Issue by gnat** [proofrock/ws4sqlite#31]
Sharing a few strategies here. Can be converted to a discussion at your discretion.

* Enabling WAL2: https://github.com/proofrock/ws4sqlite/issues/30
* Write batching / bulk **INSERT**
  * Used by rqlite (sacrifices durability for throughput).
  * Not all writes may be suitable for batching.
* Multiple databases for writes, then **ATTACH** for reads.

```yml
# main.yaml
scheduledTasks:
  - atStartup: true
    statements:
      - ATTACH 'sessions.db' as sessions
```
You can then:
```sql
SELECT count(*) FROM sessions.users;
```
Perform JOIN, etc.

Multiple databases enable you to multiply your throughput.

Share your strategies!
