### ISSUE TITLE
Issue with certain type mapping when translating results from duckdb, "Json: error calling MarshalJSON for type orderedmap.OrderedMap: json: unsupported type: duckdb.Map"

### ISSUE THREAD

**Issue by mskyttner** [proofrock/ws4sqlite#50]
See #49 for the .yaml used and for replicating this issue. There were some issues with queries 3 an 4, with complaints like this one:

```json
{"reqIdx":-1,"error":"Json: error calling MarshalJSON for type orderedmap.OrderedMap: json: unsupported type: duckdb.Map"}
```
When I tried to restrict the queries that uses the "json" extension to select columns of specific regular types it worked nicely, for example this statement did not complain:

```yaml
  - id: Q5
    sql: |
      from read_json_auto('https://api.openalex.org/works/W4388315306')
      select #3, #2, #1
```
Example where various types used in duckdb are fairly comprehensively serialized to json (I think) can be found here: https://github.com/quackscience/duckdb-extension-httpserver/pull/26/files#diff-5a3853867e339ba44486cb7f7036c326dd290818cef93b6212cf715528e3e7a7
